apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edu01-prd

resources:
- ../../base

patches:
- path: ./deployment-patch.yaml
  target:
    kind: Deployment
- path: ./ingress-patch.yaml
  target:
    kind: Ingress

images:
- name: ktdseduacr.azurecr.io/edu01/samplejava
  newName: ktdseduacr.azurecr.io/edu01/samplejava
  newTag: v2.1.2
